### ISSUE TITLE
Add Open Graph image

### ISSUE THREAD

**Issue by TomoyaKuroda** [code-mentoring/code-mentoring.github.io#32]
It's fun to add Open Graph image.
Reference https://kaydee.net/blog/open-graph-image/

**Comment by mary-boti** [comment]
Interesting idea! I am kinda very new to programming hahah could you pleas give me more details on your suggestion. Is it only for Facebook? Thanks!!

**Comment by TomoyaKuroda** [comment]
@mary-boti I think Facebook and Twitter are enough. You can use https://realfavicongenerator.net/social/ to generate the image with https://codementoring.co/images/logo.svg, but you need to convert the SVG to png first otherwise this tool doesn't work 😀. And you need to add the converted image in the assets folder. and then, you also need to add this code in _config.yml
```
# SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/image-file-name.jpg
```
Once this change is approved and merged, you will see the image here https://cards-dev.twitter.com/validator
